CREATE TABLE TB_PEDIDO
(
	NUM_PEDIDO 	INT IDENTITY(1,1) NOT NULL,
	CODCLI 		INT NULL,
	CODVEN 		SMALLINT NULL,
	DATA_EMISSAO 	DATETIME NULL,
	VLR_TOTAL 	NUMERIC(18, 2) NULL,
	SITUACAO 	VARCHAR(1) NULL,
	OBSERVACOES 	TEXT NULL,
 CONSTRAINT PK__PEDIDS PRIMARY KEY CLUSTERED (NUM_PEDIDO ASC) ON [PRIMARY]
 );
 