CREATE TABLE TB_PRODUTO
(
	ID_PRODUTO 	INT IDENTITY(1,1) NOT NULL,
	COD_PRODUTO 	VARCHAR(13) NOT NULL,
	DESCRICAO 	VARCHAR(40) NULL,
	COD_UNIDADE 	SMALLINT NULL,
	COD_TIPO 	SMALLINT NULL,
	PRECO_CUSTO 	NUMERIC(18, 4) NULL,
	PRECO_VENDA 	NUMERIC(18, 4) NULL,
	QTD_ESTIMADA 	INT NULL,
	QTD_REAL 	INT NULL,
	QTD_MINIMA 	INT NULL,
	CLAS_FISC 	VARCHAR(10) NULL,
	IPI 		INT NULL,
	PESO_LIQ 	NUMERIC(18, 2) NULL,
 CONSTRAINT PK__PRODUTS PRIMARY KEY CLUSTERED (ID_PRODUTO ASC) ON [PRIMARY]
 );
 