CREATE TABLE VENDEDOR_TBL
(
	CODVEN 		SMALLINT NOT NULL,
	NOME 		VARCHAR(50) NULL,
	FANTASIA 	VARCHAR(20) NULL,
	ENDERECO 	VARCHAR(60) NULL,
	BAIRRO 		VARCHAR(20) NULL,
	CIDADE 		VARCHAR(20) NULL,
	ESTADO 		VARCHAR(2) NULL,
	CEP 		VARCHAR(8) NULL,
	CPF 		VARCHAR(18) NULL,
	RG 		VARCHAR(15) NULL,
	FONE 		VARCHAR(15) NULL,
	FAX 		VARCHAR(15) NULL,
	E_MAIL 		VARCHAR(35) NULL,
	DATA_CAD 	DATETIME NULL,
	DATA_NASC 	DATETIME NULL,
	PORC_COMISSAO 	DECIMAL(5, 2) NULL,
 PRIMARY KEY CLUSTERED (CODVEN ASC) ON [PRIMARY]
 );

 INSERT VENDEDOR_TBL ([CODVEN], [NOME], [FANTASIA], [ENDERECO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [CPF], [RG], [FONE], [FAX], [E_MAIL], [DATA_CAD], [DATA_NASC], [PORC_COMISSAO]) VALUES (1, 'DORINHA', 'DORINHA', '1111111', NULL, NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(2.00 AS Decimal(5, 2)))
INSERT VENDEDOR_TBL ([CODVEN], [NOME], [FANTASIA], [ENDERECO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [CPF], [RG], [FONE], [FAX], [E_MAIL], [DATA_CAD], [DATA_NASC], [PORC_COMISSAO]) VALUES (2, 'MARCELO', 'MARCELO', 'CCCCCCC', NULL, NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(3.00 AS Decimal(5, 2)))
INSERT VENDEDOR_TBL ([CODVEN], [NOME], [FANTASIA], [ENDERECO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [CPF], [RG], [FONE], [FAX], [E_MAIL], [DATA_CAD], [DATA_NASC], [PORC_COMISSAO]) VALUES (3, 'LEIA', 'LEIA', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(1.00 AS Decimal(5, 2)))
INSERT VENDEDOR_TBL ([CODVEN], [NOME], [FANTASIA], [ENDERECO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [CPF], [RG], [FONE], [FAX], [E_MAIL], [DATA_CAD], [DATA_NASC], [PORC_COMISSAO]) VALUES (4, 'CELSON MARTINS', 'CELSON', 'D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST('1997-11-18T00:00:00.000' AS DateTime), CAST('1976-02-13T00:00:00.000' AS DateTime), CAST(3.00 AS Decimal(5, 2)))
INSERT VENDEDOR_TBL ([CODVEN], [NOME], [FANTASIA], [ENDERECO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [CPF], [RG], [FONE], [FAX], [E_MAIL], [DATA_CAD], [DATA_NASC], [PORC_COMISSAO]) VALUES (5, 'IRENO', 'IRENO', 'E', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(2.00 AS Decimal(5, 2)))
INSERT VENDEDOR_TBL ([CODVEN], [NOME], [FANTASIA], [ENDERECO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [CPF], [RG], [FONE], [FAX], [E_MAIL], [DATA_CAD], [DATA_NASC], [PORC_COMISSAO]) VALUES (6, 'JOAO', 'JO O', 'AV PAULISTA', NULL, NULL, 'SE', NULL, NULL, NULL, NULL, NULL, NULL, CAST('1997-11-11T00:00:00.000' AS DateTime), CAST('2000-11-11T00:00:00.000' AS DateTime), CAST(3.00 AS Decimal(5, 2)))
INSERT VENDEDOR_TBL ([CODVEN], [NOME], [FANTASIA], [ENDERECO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [CPF], [RG], [FONE], [FAX], [E_MAIL], [DATA_CAD], [DATA_NASC], [PORC_COMISSAO]) VALUES (7, 'GILSON', 'GILSON', 'JAPAO', NULL, NULL, 'JP', NULL, NULL, NULL, NULL, NULL, NULL, CAST('1997-11-11T00:00:00.000' AS DateTime), CAST('2000-11-11T00:00:00.000' AS DateTime), CAST(1.00 AS Decimal(5, 2)))
INSERT VENDEDOR_TBL ([CODVEN], [NOME], [FANTASIA], [ENDERECO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [CPF], [RG], [FONE], [FAX], [E_MAIL], [DATA_CAD], [DATA_NASC], [PORC_COMISSAO]) VALUES (8, 'GERMANO', 'GERMANO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(2.00 AS Decimal(5, 2)))